### ISSUE TITLE
chat spam if playing with trainsaver

### ISSUE THREAD

**Issue by dirkschut** [Wip-Sama/Smart_Inserters#6]
If playing this mod together with the [Train Saver](https://mods.factorio.com/mod/trainsaver) mod, the chat is spammed with the following message:
![image](https://github.com/user-attachments/assets/929d8271-c424-4c20-a917-8cd456be4429)

**Comment by dirkschut** [comment]
Might have something to do with the mod pressing / simulating pressing ctrl + t

**Comment by dirkschut** [comment]
Some more observations: Whenever it switches trains it sends the message once, but if it tries to switch and there is no train currently driving it spams the message constantly

**Comment by Wip-Sama** [comment]
![image](https://github.com/user-attachments/assets/74a45c2c-1da1-42e5-9d79-71b403778175)
That script is called for every cutscene. I didn't expect a mod to use cutscenes so intensely. I'll add a counter in the next release.

But to clarify, if that moda calls so many events that it spams, it may be using the cutscene function a bit too much.
